version: "1.0"
info:
  model: int-scaffold
packages:
- name: Crit2Project
  gitServerName: Rahul
  gitUrl: https://github.com/Rahul-Sivakumar-IBM
  gitUsername: Rahul-Sivakumar-IBM
  gitBranch: main
- name: JcHelloWorldAPI
  gitServerName: Rahul
  gitUrl: https://github.com/johnpcarter
  gitUsername: Rahul-Sivakumar-IBM
  gitBranch: main
