info:
  model: int-scaffold
packages:
- gitBranch: main
  gitServerName: Rahul
  gitUrl: https://github.com/Rahul-Sivakumar-IBM
  gitUsername: Rahul-Sivakumar-IBM
  name: Crit2Project
- gitBranch: main
  gitServerName: Rahul
  gitTag: v1.0.0
  gitUrl: https://github.com/johnpcarter
  gitUsername: Rahul-Sivakumar-IBM
  name: JcHelloWorldAPI
version: '1.0'
